# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: '15.0.2'
      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Heroku Docker Container Deploy
        # You may pin to the exact commit or the version.
        # uses: lucassarcanjo/heroku-deploy@1db4c62f6032efe526c12734f18d36669218e5af
        uses: lucassarcanjo/heroku-deploy@2.1.17
        with:
          # Email Linked to your Heroku Account
          email: ${{ secrets.EMAIL }}
          # Heroku Dyno Formation
          formation: web # optional, default is web
          # Your Heroku API Key
          api_key: ${{ secrets.API_KEY }}
          # Your Heroku App Name
          app_name: expwefit
          # Dokerfile path
          dockerfile_path: .
          # Optional build parameters
          # options: # optional
  
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
